name: deploy bracket to github pages

on:
  push:
    branches: ['main']
    paths:
      - '.github/**'
      - 'data/**'
      - 'web/**'

  # Allow manual running from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

# Allow only one concurrent deployment, skips to latest requested run once current finishes
# doesn't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    env:
      DEBIAN_FRONTEND: noninteractive

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check out Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: 'web/dist'

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
          cache-dependency-path: 'web/yarn.lock'

      - name: install dependencies with yarn
        working-directory: web
        run: yarn install

      - name: build site
        working-directory: web
        run: yarn run ci

      - name: push changes to gh-pages branch
        working-directory: web/dist
        # TODO: change user.email to somethin sane?
        run: |
          test `git branch --show-current` = 'gh-pages'
          [[ "`git status -uno`" == *"up to date with"* ]] && echo "No changes to gh-pages, not pushing." && exit 0
          git config --global user.name "${{ github.actor }} (GitHub Actions)"
          git config --global user.email "git@podaboutli.st"
          git add .
          git commit -m "build for ${{ github.ref_name }}@${GITHUB_SHA::7}"
          git push --set-upstream origin gh-pages
