name: deploy bracket to github pages

on:
  push:
    branches: ["main"]

  # Allow manual running from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

# Allow only one concurrent deployment, skips to latest requested run once current finishes
# doesn't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    env:
      DEBIAN_FRONTEND: noninteractive

    runs-on: ubuntu-latest

    steps:
      - name: install jq cli
        run: sudo apt-get install -y jq

      - uses: actions/checkout@v4

      - name: Check out Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: 'web/dist'

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
          cache-dependency-path: 'web/yarn.lock'

      - name: install dependencies with yarn
        working-directory: web
        # production=false so we get devDependencies
        run: yarn install --production=false

      - name: 'clean dist/'
        working-directory: web
        run: yarn run clean

      - name: build site
        working-directory: web
        run: yarn run build

      - name: push changes to gh-pages branch
        working-directory: web/dist
        run: |
          git config --global user.name "Audrey (GitHub Actions)"
          git config --global user.email "6566104+RalphORama@users.noreply.github.com"
          git add .
          git commit -m "automated build"
          git push --set-upstream origin gh-pages
