name: deploy bracket to github pages

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/**'
      - 'data/**'
      - 'web/**'

  # Allow manual running from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skips to latest requested run once the
# current finishes
# doesn't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
          cache-dependency-path: 'web/yarn.lock'

      - name: install dependencies with yarn
        working-directory: web
        run: yarn install

      - name: build site
        working-directory: web
        run: yarn run ci

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload build directory
          path: 'web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
